turtle = {}

turtle.forward = function() end
turtle.back = function() end
turtle.up = function() end
turtle.down = function() end
turtle.turnLeft = function() end
turtle.turnRight = function() end
turtle.dig = function(toolSide) end
turtle.digUp = function(toolSide) end
turtle.digDown = function(toolSide) end
turtle.place = function(signText) end
turtle.placeUp = function() end
turtle.placeDown = function() end
turtle.drop = function(count) end
turtle.select = function(slot) end
turtle.getItemCount = function(slot) end
turtle.getItemSpace = function(slot) end
turtle.detect = function() end
turtle.detectUp = function() end
turtle.detectDown = function() end
turtle.compare = function() end
turtle.compareUp = function() end
turtle.compareDown = function() end
turtle.attack = function(toolSide) end
turtle.attackUp = function(toolSide) end
turtle.attackDown = function(toolSide) end
turtle.dropUp = function(count) end
turtle.dropDown = function(count) end
turtle.suck = function(amount) end
turtle.suckUp = function(amount) end
turtle.suckDown = function(amount) end
turtle.getFuelLevel = function() end
turtle.refuel = function(quantity) end
turtle.compareTo = function(slot) end
turtle.transferTo = function(slot, quantity) end
turtle.getSelectedSlot = function() end
turtle.getFuelLimit = function() end
turtle.equipLeft = function() end
turtle.equipRight = function() end
turtle.inspect = function() end
turtle.inspectUp = function() end
turtle.inspectDown = function() end
turtle.getItemDetail = function(slot) end

